# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_RsltFltPln.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GUI_RsltFltPln(object):
    def setupUi(self, GUI_RsltFltPln):
        GUI_RsltFltPln.setObjectName("GUI_RsltFltPln")
        GUI_RsltFltPln.resize(800, 600)
        GUI_RsltFltPln.setMinimumSize(QtCore.QSize(800, 600))
        GUI_RsltFltPln.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(GUI_RsltFltPln)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBlock = QtWidgets.QFrame(self.centralwidget)
        self.TitleBlock.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        self.TitleBlock.setFont(font)
        self.TitleBlock.setStyleSheet("background-color: rgb(51, 58, 62);")
        self.TitleBlock.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TitleBlock.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TitleBlock.setObjectName("TitleBlock")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TitleBlock)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.TitleBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(571, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("GUI/Assets/GUI_StartScreenGraphic.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.TitleBlock)
        self.label_5.setMinimumSize(QtCore.QSize(218, 0))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(51, 58, 62);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.TitleBlock)
        self.label_6.setMinimumSize(QtCore.QSize(218, 0))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(51, 58, 62);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.TitleBlock)
        self.MainContent = QtWidgets.QFrame(self.centralwidget)
        self.MainContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MainContent.setLineWidth(0)
        self.MainContent.setObjectName("MainContent")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainContent)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.MainContent)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(161, 172, 178);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.FltPlnMonthOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.FltPlnMonthOut.setFont(font)
        self.FltPlnMonthOut.setObjectName("FltPlnMonthOut")
        self.gridLayout.addWidget(self.FltPlnMonthOut, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.FltPlnStateOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.FltPlnStateOut.setFont(font)
        self.FltPlnStateOut.setObjectName("FltPlnStateOut")
        self.gridLayout.addWidget(self.FltPlnStateOut, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.FltPlnAirportOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.FltPlnAirportOut.setFont(font)
        self.FltPlnAirportOut.setObjectName("FltPlnAirportOut")
        self.gridLayout.addWidget(self.FltPlnAirportOut, 1, 1, 1, 1)
        self.FltPlnETypeOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.FltPlnETypeOut.setFont(font)
        self.FltPlnETypeOut.setObjectName("FltPlnETypeOut")
        self.gridLayout.addWidget(self.FltPlnETypeOut, 0, 3, 1, 1)
        self.FltPlnENoOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.FltPlnENoOut.setFont(font)
        self.FltPlnENoOut.setObjectName("FltPlnENoOut")
        self.gridLayout.addWidget(self.FltPlnENoOut, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.FltPlnPhaseOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.FltPlnPhaseOut.setFont(font)
        self.FltPlnPhaseOut.setObjectName("FltPlnPhaseOut")
        self.gridLayout.addWidget(self.FltPlnPhaseOut, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 4, 1, 1)
        self.FltPlnTODOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.FltPlnTODOut.setFont(font)
        self.FltPlnTODOut.setObjectName("FltPlnTODOut")
        self.gridLayout.addWidget(self.FltPlnTODOut, 1, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.FltPlnOutput = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.FltPlnOutput.setFont(font)
        self.FltPlnOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.FltPlnOutput.setObjectName("FltPlnOutput")
        self.verticalLayout_2.addWidget(self.FltPlnOutput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_18 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.FltPlnACOut1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.FltPlnACOut1.setFont(font)
        self.FltPlnACOut1.setObjectName("FltPlnACOut1")
        self.gridLayout_2.addWidget(self.FltPlnACOut1, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.FltPlnACOut2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.FltPlnACOut2.setFont(font)
        self.FltPlnACOut2.setObjectName("FltPlnACOut2")
        self.gridLayout_2.addWidget(self.FltPlnACOut2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.FltPlnACOut3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.FltPlnACOut3.setFont(font)
        self.FltPlnACOut3.setObjectName("FltPlnACOut3")
        self.gridLayout_2.addWidget(self.FltPlnACOut3, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.FltPlnACOut4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.FltPlnACOut4.setFont(font)
        self.FltPlnACOut4.setObjectName("FltPlnACOut4")
        self.gridLayout_2.addWidget(self.FltPlnACOut4, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.FltPlnACOut5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.FltPlnACOut5.setFont(font)
        self.FltPlnACOut5.setObjectName("FltPlnACOut5")
        self.gridLayout_2.addWidget(self.FltPlnACOut5, 4, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.MainContent)
        self.ButtonBar = QtWidgets.QFrame(self.centralwidget)
        self.ButtonBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ButtonBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ButtonBar.setLineWidth(0)
        self.ButtonBar.setObjectName("ButtonBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ButtonBar)
        self.horizontalLayout_4.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.StartButton = QtWidgets.QPushButton(self.ButtonBar)
        self.StartButton.setMinimumSize(QtCore.QSize(100, 50))
        self.StartButton.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.StartButton.setFont(font)
        self.StartButton.setStyleSheet("background-color: rgb(101, 117, 125);\n"
"color: rgb(255, 255, 255);")
        self.StartButton.setObjectName("StartButton")
        self.horizontalLayout_4.addWidget(self.StartButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.QuitButton = QtWidgets.QPushButton(self.ButtonBar)
        self.QuitButton.setMinimumSize(QtCore.QSize(100, 50))
        self.QuitButton.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.QuitButton.setFont(font)
        self.QuitButton.setStyleSheet("background-color: rgb(101, 117, 125);\n"
"color: rgb(255, 255, 255);")
        self.QuitButton.setObjectName("QuitButton")
        self.horizontalLayout_4.addWidget(self.QuitButton)
        self.verticalLayout.addWidget(self.ButtonBar)
        GUI_RsltFltPln.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GUI_RsltFltPln)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        GUI_RsltFltPln.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GUI_RsltFltPln)
        self.statusbar.setObjectName("statusbar")
        GUI_RsltFltPln.setStatusBar(self.statusbar)

        self.retranslateUi(GUI_RsltFltPln)
        QtCore.QMetaObject.connectSlotsByName(GUI_RsltFltPln)

    def retranslateUi(self, GUI_RsltFltPln):
        _translate = QtCore.QCoreApplication.translate
        GUI_RsltFltPln.setWindowTitle(_translate("GUI_RsltFltPln", "MainWindow"))
        self.label_5.setText(_translate("GUI_RsltFltPln", "Bird Strike Analysis"))
        self.label_6.setText(_translate("GUI_RsltFltPln", "AME505 Group 8"))
        self.label_2.setText(_translate("GUI_RsltFltPln", "State"))
        self.FltPlnMonthOut.setText(_translate("GUI_RsltFltPln", "FltPlnMonthOut"))
        self.label_8.setText(_translate("GUI_RsltFltPln", "# of Engines"))
        self.FltPlnStateOut.setText(_translate("GUI_RsltFltPln", "FltPlnStateOut"))
        self.label_14.setText(_translate("GUI_RsltFltPln", "Airport"))
        self.FltPlnAirportOut.setText(_translate("GUI_RsltFltPln", "FltPlnAirportOut"))
        self.FltPlnETypeOut.setText(_translate("GUI_RsltFltPln", "FltPlnETypeOut"))
        self.FltPlnENoOut.setText(_translate("GUI_RsltFltPln", "FltPlnENoOut"))
        self.label_4.setText(_translate("GUI_RsltFltPln", "Engine Type"))
        self.label_10.setText(_translate("GUI_RsltFltPln", "Month"))
        self.label_12.setText(_translate("GUI_RsltFltPln", "Phase of Flight"))
        self.FltPlnPhaseOut.setText(_translate("GUI_RsltFltPln", "FltPlnPhaseOut"))
        self.label_17.setText(_translate("GUI_RsltFltPln", "Time of Day"))
        self.FltPlnTODOut.setText(_translate("GUI_RsltFltPln", "FltPlnTODOut"))
        self.label_16.setText(_translate("GUI_RsltFltPln", "Based on the above conditions, the aircraft class is"))
        self.FltPlnOutput.setText(_translate("GUI_RsltFltPln", "FltPlnOutput"))
        self.label_18.setText(_translate("GUI_RsltFltPln", "The five most commonly hit aircraft per the given parameters and within this class are"))
        self.label_3.setText(_translate("GUI_RsltFltPln", "1"))
        self.FltPlnACOut1.setText(_translate("GUI_RsltFltPln", "FltPlnACOut1"))
        self.label_7.setText(_translate("GUI_RsltFltPln", "2"))
        self.FltPlnACOut2.setText(_translate("GUI_RsltFltPln", "FltPlnACOut2"))
        self.label_9.setText(_translate("GUI_RsltFltPln", "3"))
        self.FltPlnACOut3.setText(_translate("GUI_RsltFltPln", "FltPlnACOut3"))
        self.label_11.setText(_translate("GUI_RsltFltPln", "4"))
        self.FltPlnACOut4.setText(_translate("GUI_RsltFltPln", "FltPlnACOut4"))
        self.label_13.setText(_translate("GUI_RsltFltPln", "5"))
        self.FltPlnACOut5.setText(_translate("GUI_RsltFltPln", "FltPlnACOut5"))
        self.StartButton.setText(_translate("GUI_RsltFltPln", "Back"))
        self.QuitButton.setText(_translate("GUI_RsltFltPln", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI_RsltFltPln = QtWidgets.QMainWindow()
    ui = Ui_GUI_RsltFltPln()
    ui.setupUi(GUI_RsltFltPln)
    GUI_RsltFltPln.show()
    sys.exit(app.exec_())
